version: "2"

checks:
  method-lines:
    enabled: false

plugins:
  eslint:
    enabled: true
    channel: eslint-4
  markdownlint:
    enabled: true
    checks:
      MD013:
        enabled: false
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: php
      standard: WordPress
      ignore_warnings: false

exclude_patterns:
- "**/node_modules/"
- "vendor/"
- "dist/"
- "src/css/slickQuiz.css"
- "src/js/slickQuiz.js"
