version: "2"

checks:
  argument-count:
    enabled: false
  complex-logic:
    enabled: false
  file-lines:
    enabled: false
  method-complexity:
    enabled: false
  method-count:
    enabled: false
  method-lines:
    enabled: false
  nested-control-flow:
    enabled: false
  return-statements:
    enabled: false
  similar-code:
    enabled: false
  identical-code:
    enabled: false

plugins:
  eslint:
    enabled: true
    channel: eslint-4
  phpcodesniffer:
    enabled: true
    config:
      file_extensions: php
      standard: WordPress
      ignore_warnings: false

exclude_patterns:
- "**/node_modules/"
- "vendor/"
- "dist/"
- "src/css/slickQuiz.css"
- "src/js/slickQuiz.js"
